# --- 認証設定 ---
# Basic 認証を有効にすると、PWが平文でインターネットに流れてしまい、逆に脆弱になるリスクがあるため、オフにする
# auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
# auth_param basic children 5
# auth_param basic realm Cloud Proxy Server
# auth_param basic credentialsttl 2 hours
# 
# acl authenticated proxy_auth REQUIRED

# --- ポート・接続制限 ---
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# --- Proxy利用元IP ---
# 基本はociで行う 2重管理しない事とする

# --- whitelist ---
acl whitelist dstdomain "/etc/squid/whitelist"

# --- アクセス制御 ---
http_access allow whitelist
http_access deny all

# --- 待ち受けポート ---
http_port 3128

# --- キャッシュ・匿名化 ---
cache deny all
forwarded_for off
request_header_access Via deny all
request_header_access X-Forwarded-For deny all

# --- ログフォーマット ---
logformat proxylog %{%Y/%m/%d %H:%M:%S}tl %>a %Ss %rm %ru %03>Hs %Sh/%<a
access_log daemon:/var/log/squid/access.log proxylog
